import type { Comment, PollOption } from "../types";
export class ApiError extends Error { status:number; constructor(message:string,status=500){super(message);this.status=status;} }
const ago=(m:number)=>new Date(Date.now()-m*60000).toISOString();
const commentsByPost=new Map<string,Comment[]>([
["demo-announcement",[{id:"comment-ann-1",postId:"demo-announcement",authorUid:"demo-beatriz",authorName:"Beatriz Alves",text:"Ótima novidade! O benefício também contempla dependentes?",reactionCount:6,createdAt:ago(24)},{id:"comment-ann-2",postId:"demo-announcement",authorUid:"demo-mariana",authorName:"Mariana Costa",text:"Sim. Até três dependentes, com contratação direto pelo aplicativo.",reactionCount:9,createdAt:ago(18)}]],
["demo-question",[{id:"comment-question-1",postId:"demo-question",authorUid:"demo-beatriz",authorName:"Beatriz Alves",text:"Mapeamos o fluxo e vimos que o maior atraso estava na coleta inicial. Centralizamos o checklist e automatizamos o primeiro contato; a ativação caiu para 2,6 dias.\n[[uorqui-photo:demo-solution-photo-1]]",reactionCount:24,createdAt:ago(46)},{id:"comment-question-2",postId:"demo-question",authorUid:"demo-joao",authorName:"João Lima",text:"Consigo criar um gatilho no CRM e deixar os dados básicos pré-preenchidos.\n[[uorqui-photo:demo-solution-photo-2]]",reactionCount:11,createdAt:ago(35)},{id:"comment-question-mine",postId:"demo-question",authorUid:"demo-me",authorName:"Daniel Carvalho",text:"Vamos testar com os próximos dez clientes e comparar com a coorte atual.",reactionCount:7,liked:true,createdAt:ago(22)}]],
["demo-event",[{id:"comment-event-1",postId:"demo-event",authorUid:"demo-ana",authorName:"Ana Ribeiro",text:"Quem estiver em visita poderá acompanhar a gravação depois?",reactionCount:3,createdAt:ago(82)}]],
["demo-world",[{id:"comment-world-1",postId:"demo-world",authorUid:"demo-lucas",authorName:"Lucas Martins",text:"Ficou excelente — e já gerou boas conversas com o mercado.",reactionCount:14,createdAt:ago(170)}]]]);
const polls=new Map<string,PollOption[]>();
function bodyOf(init:RequestInit){try{return typeof init.body==="string"?JSON.parse(init.body):{};}catch{return{};}}
export async function api<T=any>(path:string,init:RequestInit={}):Promise<T>{const method=String(init.method||"GET").toUpperCase();const cm=path.match(/^\/posts\/([^/?]+)\/comments/);if(cm&&method==="GET")return{comments:[...(commentsByPost.get(cm[1])||[])]}as T;if(cm&&method==="POST"){const text=String(bodyOf(init).text||"").trim();const c:Comment={id:`demo-comment-${Date.now()}`,postId:cm[1],authorUid:"demo-me",authorName:"Daniel Carvalho",text,reactionCount:0,createdAt:new Date().toISOString()};commentsByPost.set(cm[1],[...(commentsByPost.get(cm[1])||[]),c]);return{comment:c}as T;}if(path.includes("/solution")||path.includes("/resolve"))return{ok:true}as T;const pm=path.match(/^\/posts\/([^/]+)\/poll-vote$/);if(pm&&method==="POST")return{optionId:String(bodyOf(init).optionId||""),pollOptions:polls.get(pm[1])||[],pollTotalVotes:0}as T;return{ok:true}as T;}
const mediaUrls=new Map<string,string>([["demo-solution-photo-1","https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80"],["demo-solution-photo-2","https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80"]]);
export function cachedMediaBlobUrl(id:string){return mediaUrls.get(id)||"";}export function cacheMediaBlobUrl(id:string,blob:Blob){const url=URL.createObjectURL(blob);mediaUrls.set(id,url);return url;}export async function mediaBlobUrl(id:string){const url=mediaUrls.get(id);if(url)return url;throw new ApiError("Mídia não disponível na demonstração.",404);}export async function prefetchPostMedia(){ }
